project_id = "xbfwwtfnnpksjyolgpxe"

[functions.send-booking-confirmation]
verify_jwt = false

[functions.send-owner-notification]
verify_jwt = false

[functions.handle-booking-action]
verify_jwt = false
