// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xbfwwtfnnpksjyolgpxe.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhiZnd3dGZubnBrc2p5b2xncHhlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA1ODY5NTAsImV4cCI6MjA2NjE2Mjk1MH0.77v2iWjMFlFMdTDTxGuL_5M4eIMYxM-B9F101x8At9g";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);